name: MolOPTGA
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.0=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - smina=2017.11.9=0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - annotated-types==0.7.0
    - attrs==25.3.0
    - bel-resources==0.0.3
    - bioregistry==0.12.22
    - certifi==2022.12.7
    - charset-normalizer==2.1.1
    - click==8.2.1
    - click-plugins==1.1.1.2
    - cloudpickle==3.1.1
    - curies==0.10.19
    - deepchem==2.8.0
    - dgl==2.4.0+cu118
    - dgllife==0.3.2
    - dnspython==2.7.0
    - email-validator==2.2.0
    - filelock==3.13.1
    - fsspec==2024.6.1
    - future==1.0.0
    - greenlet==3.2.3
    - humanize==4.12.3
    - hyperopt==0.2.7
    - idna==3.4
    - jinja2==3.1.4
    - joblib==1.4.2
    - jsonschema==4.24.0
    - jsonschema-specifications==2025.4.1
    - markupsafe==2.1.5
    - more-click==0.1.2
    - more-itertools==10.7.0
    - mpmath==1.3.0
    - multisplitby==0.0.1
    - networkx==3.3
    - numpy==1.26.3
    - openbabel-wheel==3.1.1.22
    - packaging==24.2
    - pandas==2.2.3
    - pillow==11.0.0
    - psutil==7.0.0
    - psycopg2-binary==2.9.10
    - py4j==0.10.9.9
    - pybel==0.15.5
    - pydantic==2.11.1
    - pydantic-core==2.33.0
    - pyparsing==3.2.3
    - pystow==0.7.1
    - python-dateutil==2.9.0.post0
    - pytrie==0.4.0
    - pytz==2025.2
    - pyyaml==6.0.2
    - ratelimit==2.2.1
    - rdkit==2024.9.6
    - referencing==0.36.2
    - requests==2.28.1
    - requests-file==2.1.0
    - rpds-py==0.26.0
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - six==1.17.0
    - sortedcontainers==2.4.0
    - sqlalchemy==2.0.41
    - sympy==1.13.1
    - tabulate==0.9.0
    - threadpoolctl==3.6.0
    - torch==2.1.2+cu118
    - torchaudio==2.1.2+cu118
    - torchvision==0.16.2+cu118
    - tqdm==4.67.1
    - triton==2.1.0
    - typing-extensions==4.12.2
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - urllib3==1.26.13
    